### ISSUE TITLE
call-rate stats

### ISSUE THREAD

**Issue by seru71** [MNMdiagnostics/NaszeGenomy#5]
Can it be generated by PLINK? BCFtools?
- [x] histogram of variant sites with missing call (call-rate on X, # variants on Y) (1082 individuals)
- [x] histogram of call-rate per genome (call-rate on X, # genomes on Y) before 0.9 filtering (1082 individuals)
- [x]  histogram of call-rate per genome (call-rate on X, # genomes on Y) after 0.9 filtering (943 individuals)

**Comment by sypniewski20** [comment]
Done
